language: cpp
compiler: gcc
dist: bionic

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
        - sudo apt-get install -qq libgtest-dev build-essential qtcreator g++-5
        - sudo update-alternatives --set c++ /usr/bin/g++
        - ( cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp libgtest* /usr/lib/ )
script:
        - qmake
        - make
        - ./bin/raytracing
