language: cpp
compiler: gcc
dist: bionic

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install: 
  - sudo apt-get install -qq g++-6 libgtest-dev build-essential qtcreator
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - ( cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp libgtest* /usr/lib/ )
script:
  - qmake
  - make
  - ./bin/raytracing

