language: cpp
compiler: gcc
dist: bionic

before_install:
        - sudo apt-get update
        - sudo apt-get install -y libgtest-dev
        - ( cd /usr/src/googletest/googletest && sudo mkdir build && cd build && sudo cmake .. && sudo make && sudo cp libgtest* /usr/lib/ )
script:
        - qmake -project
        - qmake raytracing.pro
        - make
