language: cpp
compiler: gcc
dist: bionic

before_install:
        - sudo apt-get update
        - sudo apt-get install -y libgtest-dev build-essential qtcreator
        - ( cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp libgtest* /usr/lib/ )
script:
        - qmake
        - make
        - ./bin/raytracing
