language: cpp
compiler: gcc
dist: bionic

before_install:
        - sudo apt-get update
        - sudo apt-get install -y libgtest-dev
script:
        - qmake -project
        - qmake raytracing.pro
        - make
